services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: yarn run start
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      REDIS_URL: "redis://redis:6379"
      PORT: 3001

  redis:
    image: redis
    ports:
      - "6379:6379"

